export const countyOptions = [
    "Matagorda",
    "Bowie",
    "Gonzales",
    "Wichita",
    "Ellis",
    "Henderson",
    "Grayson",
    "Guadalupe",
    "Brown",
    "Gregg",
    "Angelina",
    "Nacogdoches",
    "Jefferson",
    "Tom Green",
    "Bee",
    "Hunt",
    "Comal",
    "Gillespie",
    "De Witt",
    "Lavaca",
    "Hays",
    "Jim Wells",
    "Harris",
    "Hidalgo",
    "San Patricio",
    "Fort Bend",
    "Dallas",
    "Walker",
    "Kleberg",
    "Taylor",
    "Ector",
    "Cameron",
    "Victoria",
    "Harrison",
    "Zavala",
    "Denton",
    "Brooks",
    "Houston",
    "Kerr",
    "El Paso",
    "Johnson",
    "La Salle",
    "Bailey",
    "Nueces",
    "Navarro",
    "Caldwell",
    "Dimmit",
    "Lee",
    "Goliad",
    "Freestone",
    "Webb",
    "Wilbarger",
    "Lamar",
    "Hood",
    "Calhoun",
    "Williamson",
    "Wharton",
    "Polk",
    "Parker",
    "Zapata",
    "Bexar",
    "Hale",
    "Montgomery",
    "Howard",
    "Orange",
    "Reeves",
    "Cooke",
    "Hockley",
    "Brazoria",
    "Midland",
    "Shelby",
    "Tarrant",
    "Atascosa",
    "Smith",
    "Potter",
    "Maverick",
    "Brazos",
    "Val Verde",
    "Erath",
    "Bell",
    "Bastrop",
    "Travis",
    "Jasper",
    "Llano",
    "Terry",
    "Jim Hogg",
    "Collin",
    "Lubbock",
    "Starr",
    "Titus",
    "Galveston",
    "Mclennan",
    "Hopkins",
    "Kaufman",
    "Uvalde",
    "Young",
    "Milam",
    "Liberty",
];

export const programTypeOptions = [
    "Affiliate Center",
    "Comprehensive Center",
    "ReEntry Program Provider"
];
